name: Auto add label

on:
  pull_request:
    types: [opened, edited]

jobs:
  add-labels:
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'fix')
    steps:
      - name: Add labels
        uses: actions-cool/issues-helper@main
        with:
          actions: 'add-labels'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          labels: 'pr(fix)'
